### ISSUE TITLE
LTI 1.1 Outcomes - cannot read key error

### ISSUE THREAD

**Issue by ShannonH** [blackboard/BBDN-LTI-Tool-Provider-Node#108]
```
TypeError: Cannot read property 'key' of undefined
    at Object.outcomes (/usr/app/server/lib/app/lti.js:307:54)
    at /usr/app/server/lib/app/routes.js:113:9
    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/app/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/usr/app/node_modules/cookie-parser/index.js:57:14)
```

The value for the lti 1.1 app key isn't being pulled from the config file properly

server/src/app/lti.js:13
server/src/app/lti.js:282

Steps to repro:
1. Use this tool to add a graded LTI link in an original Learn course
2. Log in as a student
3. Launch the link from the course
Expected: Page where point values can be entered should be shown
Observed: Above error shows

**Comment by scollovati** [comment]
Not clear if releated to this, but when you enter into the Outcomes page and you fill the boxes and POST/READ grades with a valid student's sourcedId the tool always returns an error like `Error: Incorrect sourcedId:[bbtest]`, where `bbtest` it's an enrolled sourcedId in the course.
