### ISSUE TITLE
not working on node 18 

### ISSUE THREAD

**Issue by alkahtani** [blackboard/BBDN-LTI-Tool-Provider-Node#156]
I got an error when running this project on node 18 , here is the error 

[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (D:\my-projects\BBDN-LTI-Tool-Provider-Node\node_modules\webpack\lib\util\createHash.js:155:18)
    at BulkUpdateDecorator.digest (D:\my-projects\BBDN-LTI-Tool-Provider-Node\node_modules\webpack\lib\util\createHash.js:80:21)
    at D:\my-projects\BBDN-LTI-Tool-Provider-Node\node_modules\webpack\lib\DefinePlugin.js:595:38
    at _next24 (eval at create (D:\my-projects\BBDN-LTI-Tool-Provider-Node\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:44:1)
    at _next2 (eval at create (D:\my-projects\BBDN-LTI-Tool-Provider-Node\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (D:\my-projects\BBDN-LTI-Tool-Provider-Node\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:105:1)
    at Hook.CALL_DELEGATE [as _call] (D:\my-projects\BBDN-LTI-Tool-Provider-Node\node_modules\tapable\lib\Hook.js:14:14)    at Compiler.newCompilation (D:\my-projects\BBDN-LTI-Tool-Provider-Node\node_modules\webpack\lib\Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by deisner** [comment]
This fixed it for me:

`npm audit fix --force`

See https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported/73027407#73027407

**Comment by alkahtani** [comment]
@deisner , many thanks , i will check and update
